version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: salary_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salary_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: salary_redis_broker
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salary_fastapi_backend
    command: uvicorn backend:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      # Пробрасываем веса моделей в контейнер
      - C:\Users\Asus\OneDrive\Рабочий стол\Project ML ITMO\Модуль №3 ML System Design and MFDP\MFDP\models:/app/models
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/salary_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  # ML-воркеры
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A scripts.workers.celery_app worker --loglevel=info
    volumes:
      - .:/app
      # Пробрасывем веса модели для инференса в воркер
      - C:\Users\Asus\OneDrive\Рабочий стол\Project ML ITMO\Модуль №3 ML System Design and MFDP\MFDP\models:/app/models
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/salary_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: salary_streamlit_ui
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  postgres_data: