services:
  db:
    image: postgres:15-alpine
    container_name: salary_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salary_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - salary_network

  redis:
    image: redis:7-alpine
    container_name: salary_redis_broker
    ports:
      - "6379:6379"
    networks:
      - salary_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salary_fastapi_backend
    command: uvicorn backend:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./models:/app/models
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/salary_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - salary_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salary_celery_worker
    command: celery -A scripts.workers.celery_app worker --loglevel=info --pool=solo
    volumes:
      - .:/app
      - ./models:/app/models
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/salary_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db
    networks:
      - salary_network

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: salary_streamlit_ui
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - salary_network

# Явно определяем общую сеть
networks:
  salary_network:
    driver: bridge

volumes:
  postgres_data: